#!/usr/bin/env ruby
require 'fileutils'

def cwd
  @cwd ||= File.expand_path(File.dirname(__FILE__))
end

def root
  File.dirname(cwd)
end

def home
  @home ||= File.expand_path('~')
end

def destination(file,sub_directory)
  File.join(*[home, sub_directory, File.basename(file)].compact)
end

def install(file)
  if system("ln -nsf #{root}/#{file} #{home}/#{file}")
    print "successfully installed "
  else
    print "failed to install "
  end
  puts file
end

def uninstall(file)
  file = File.join(home, file)
  return puts "no file at #{file}" unless File.exist?(file)
  if File.symlink?(file)
    File.unlink(file)
    puts "removed symlink at #{file}"
  else
    puts "could not remove non-symlink at #{file}"
  end
end

def uninstall?
  ARGV.include?('-u')
end

if ARGV.include?('-h')
  script = File.basename(__FILE__)
  puts %[
  "#{script}" symlinks the files in dotmatrix into your home directory.
  options:
      -h  Get this help
      -u  Remove symlinks to files in dotmatrix
  ]
  exit 0
end

home_files = Dir.entries(root) - %w(bin script . .. .git)
bin_files = Dir.entries(File.join(root, 'bin')) - %w(. ..)

FileUtils.mkdir_p(File.join(home,'bin'))

(home_files + bin_files).each do |file|
  next if file =~ /~$/
  uninstall? ? uninstall(file) : install(file)
end
